create extension if not exists pgcrypto;

-- Drop in safe order
DROP TABLE IF EXISTS public.room_players CASCADE;
DROP TABLE IF EXISTS public.rooms CASCADE;
DROP TABLE IF EXISTS public.game_cards CASCADE;
DROP TABLE IF EXISTS public.game_tiles CASCADE;
DROP TABLE IF EXISTS public.game_items CASCADE;
DROP TABLE IF EXISTS public.game_config CASCADE;

create table public.game_config (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table public.game_items (
  id bigint generated by default as identity primary key,
  sort_order integer not null default 0,
  name text not null,
  icon text not null default '🎁',
  price integer not null default 0,
  description text not null default '',
  accent_color text not null default '#3d5afe',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.game_tiles (
  id bigint generated by default as identity primary key,
  sort_order integer not null unique,
  name text not null,
  short_name text not null default '',
  kind text not null default 'neutral',
  icon text not null default '⬢',
  description text not null default '',
  amount integer not null default 0,
  skip_turns integer not null default 0,
  move_steps integer not null default 0,
  card_group text not null default 'chance',
  buy_item_ids jsonb not null default '[]'::jsonb,
  gift_item_ids jsonb not null default '[]'::jsonb,
  buy_pick_limit integer not null default 1,
  gift_count integer not null default 1,
  board_x integer,
  board_y integer,
  next_tile_id bigint null,
  accent_color text not null default '',
  text_color text not null default '',
  created_at timestamptz not null default now()
);

create table public.game_cards (
  id bigint generated by default as identity primary key,
  sort_order integer not null default 0,
  card_group text not null default 'chance',
  title text not null,
  body text not null default '',
  icon text not null default '💌',
  amount integer not null default 0,
  skip_turns integer not null default 0,
  move_steps integer not null default 0,
  buy_item_ids jsonb not null default '[]'::jsonb,
  gift_item_ids jsonb not null default '[]'::jsonb,
  buy_pick_limit integer not null default 1,
  gift_count integer not null default 1,
  accent_color text not null default '',
  text_color text not null default '',
  created_at timestamptz not null default now()
);

alter table public.game_tiles
  add constraint game_tiles_next_tile_fk
  foreign key (next_tile_id) references public.game_tiles(id) on delete set null;

create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  status text not null default 'lobby',
  host_client_id text not null,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.room_players (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  client_id text not null,
  name text not null,
  seat_no integer not null default 0,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(room_id, client_id)
);

insert into public.game_config(key, value) values
('game_title', '{"value":"Gazdálkodj Pajkosan"}'),
('game_subtitle', '{"value":"Stabil alapverzió."}'),
('currency_name', '{"value":"Ft"}'),
('starting_money', '{"value":3000}'),
('pass_start_bonus', '{"value":400}'),
('land_start_bonus', '{"value":800}'),
('board_cols', '{"value":10}'),
('board_rows', '{"value":10}'),
('animation_ms_per_step', '{"value":430}');

insert into public.game_items (sort_order, name, icon, price, description, accent_color) values
(1, 'Rózsa', '🌹', 350, 'Kedves kis ajándék.', '#d14b7c'),
(2, 'Csoki', '🍫', 500, 'Édes plusz.', '#9a613a'),
(3, 'Parfüm', '🧴', 700, 'Stílusos választás.', '#6d5bd0'),
(4, 'Pezsgő', '🍾', 900, 'Ünneplős cucc.', '#2c9c6a'),
(5, 'Hangulatfény', '🕯️', 650, 'Jól néz ki.', '#4667d6'),
(6, 'Ajándékdoboz', '🎁', 800, 'Valami biztos lesz benne.', '#cc6b39');

insert into public.game_tiles (
  sort_order, name, short_name, kind, icon, description, amount, skip_turns, move_steps,
  card_group, buy_item_ids, gift_item_ids, buy_pick_limit, gift_count, board_x, board_y, accent_color, text_color
) values
(1, 'Start', 'START', 'start', '🚩', 'Innen indul minden.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 0, 0, '#855f22', '#fff5d4'),
(2, 'Bónusz', '+500', 'money', '💸', 'Kapsz 500 Ft-ot.', 500, 0, 0, 'chance', '[]', '[]', 1, 1, 1, 0, '#2e8b57', '#f2fff8'),
(3, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 2, 0, '#944a88', '#fff1fd'),
(4, 'Kis bolt', 'BOLT', 'shop', '🛒', 'Válassz 1 tárgyat.', 0, 0, 0, 'chance', '[1,2,5]', '[]', 1, 1, 3, 0, '#8c6227', '#fff7e8'),
(5, 'Bünti', '-400', 'money', '💥', 'Fizess 400 Ft-ot.', -400, 0, 0, 'chance', '[]', '[]', 1, 1, 4, 0, '#9a3f54', '#fff0f3'),
(6, 'Ajándék', 'AJI', 'gift', '🎁', 'Kapsz 1 random tárgyat.', 0, 0, 0, 'chance', '[]', '[1,2,3,4,5,6]', 1, 1, 5, 0, '#4762cc', '#eef2ff'),
(7, 'Lépj előre', '+2', 'move', '➡️', 'Lépj előre 2 mezőt.', 0, 0, 2, 'chance', '[]', '[]', 1, 1, 6, 0, '#5b52b4', '#f3efff'),
(8, 'Kimaradsz', 'SKIP', 'skip', '😵', '1 körből kimaradsz.', 0, 1, 0, 'chance', '[]', '[]', 1, 1, 7, 0, '#9a3f54', '#fff0f3'),
(9, 'Bolt+', 'BOLT', 'shop', '🛍️', 'Válassz 2 tárgyból 1-et.', 0, 0, 0, 'chance', '[3,4,6]', '[]', 1, 1, 8, 0, '#8c6227', '#fff7e8'),
(10, 'Nagy bónusz', '+800', 'money', '💰', 'Kapsz 800 Ft-ot.', 800, 0, 0, 'chance', '[]', '[]', 1, 1, 9, 0, '#2e8b57', '#f2fff8'),
(11, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 9, 1, '#944a88', '#fff1fd'),
(12, 'Hátra', '-2', 'move', '↩️', 'Lépj vissza 2 mezőt.', 0, 0, -2, 'chance', '[]', '[]', 1, 1, 9, 2, '#5b52b4', '#f3efff'),
(13, 'Semmi', 'PIHI', 'neutral', '😌', 'Ezen a mezőn nem történik semmi.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 9, 3, '#425378', '#eef4ff'),
(14, 'Ajándék+', 'AJI', 'gift', '🎉', 'Kapsz 2 random tárgyat.', 0, 0, 0, 'chance', '[]', '[1,2,3,4,5,6]', 1, 2, 9, 4, '#4762cc', '#eef2ff'),
(15, 'Minusz', '-600', 'money', '🧾', 'Fizess 600 Ft-ot.', -600, 0, 0, 'chance', '[]', '[]', 1, 1, 9, 5, '#9a3f54', '#fff0f3'),
(16, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 9, 6, '#944a88', '#fff1fd'),
(17, 'Bolt', 'BOLT', 'shop', '🛒', 'Válassz 2 tárgyból 1-et.', 0, 0, 0, 'chance', '[1,3,4,5]', '[]', 1, 1, 9, 7, '#8c6227', '#fff7e8'),
(18, 'Kimaradsz', 'SKIP', 'skip', '🥴', '2 körből kimaradsz.', 0, 2, 0, 'chance', '[]', '[]', 1, 1, 9, 8, '#9a3f54', '#fff0f3'),
(19, 'Bónusz', '+900', 'money', '🔥', 'Kapsz 900 Ft-ot.', 900, 0, 0, 'chance', '[]', '[]', 1, 1, 9, 9, '#2e8b57', '#f2fff8'),
(20, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 8, 9, '#944a88', '#fff1fd'),
(21, 'Bolt', 'BOLT', 'shop', '🛏️', 'Válassz 1 tárgyat.', 0, 0, 0, 'chance', '[2,4,5,6]', '[]', 1, 1, 7, 9, '#8c6227', '#fff7e8'),
(22, 'Minusz', '-500', 'money', '💢', 'Fizess 500 Ft-ot.', -500, 0, 0, 'chance', '[]', '[]', 1, 1, 6, 9, '#9a3f54', '#fff0f3'),
(23, 'Előre', '+3', 'move', '🏃', 'Lépj előre 3 mezőt.', 0, 0, 3, 'chance', '[]', '[]', 1, 1, 5, 9, '#5b52b4', '#f3efff'),
(24, 'Ajándék', 'AJI', 'gift', '🎁', 'Kapsz 1 random tárgyat.', 0, 0, 0, 'chance', '[]', '[1,2,3,4,5,6]', 1, 1, 4, 9, '#4762cc', '#eef2ff'),
(25, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 3, 9, '#944a88', '#fff1fd'),
(26, 'Bónusz', '+700', 'money', '🪙', 'Kapsz 700 Ft-ot.', 700, 0, 0, 'chance', '[]', '[]', 1, 1, 2, 9, '#2e8b57', '#f2fff8'),
(27, 'Bolt', 'BOLT', 'shop', '🛍️', 'Válassz 1 tárgyat.', 0, 0, 0, 'chance', '[1,2,3,4,5,6]', '[]', 1, 1, 1, 9, '#8c6227', '#fff7e8'),
(28, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 0, 9, '#944a88', '#fff1fd'),
(29, 'Minusz', '-300', 'money', '💣', 'Fizess 300 Ft-ot.', -300, 0, 0, 'chance', '[]', '[]', 1, 1, 0, 8, '#9a3f54', '#fff0f3'),
(30, 'Ajándék', 'AJI', 'gift', '🎊', 'Kapsz 1 random tárgyat.', 0, 0, 0, 'chance', '[]', '[1,2,3,4,5,6]', 1, 1, 0, 7, '#4762cc', '#eef2ff'),
(31, 'Semmi', 'PIHI', 'neutral', '😌', 'Pihi.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 0, 6, '#425378', '#eef4ff'),
(32, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 0, 5, '#944a88', '#fff1fd'),
(33, 'Bolt', 'BOLT', 'shop', '🛒', 'Válassz 1 tárgyat.', 0, 0, 0, 'chance', '[3,4,5]', '[]', 1, 1, 0, 4, '#8c6227', '#fff7e8'),
(34, 'Bónusz', '+600', 'money', '✨', 'Kapsz 600 Ft-ot.', 600, 0, 0, 'chance', '[]', '[]', 1, 1, 0, 3, '#2e8b57', '#f2fff8'),
(35, 'Hátra', '-1', 'move', '↪️', 'Lépj vissza 1 mezőt.', 0, 0, -1, 'chance', '[]', '[]', 1, 1, 0, 2, '#5b52b4', '#f3efff'),
(36, 'Pakli', 'PAKLI', 'card', '💌', 'Húzz egy lapot.', 0, 0, 0, 'chance', '[]', '[]', 1, 1, 0, 1, '#944a88', '#fff1fd');

update public.game_tiles t
set next_tile_id = coalesce(
  (select id from public.game_tiles nx where nx.sort_order = t.sort_order + 1),
  (select id from public.game_tiles s where s.sort_order = 1)
);

insert into public.game_cards (
  sort_order, card_group, title, body, icon, amount, skip_turns, move_steps,
  buy_item_ids, gift_item_ids, buy_pick_limit, gift_count, accent_color, text_color
) values
(1, 'chance', 'Jutalom', 'Kapsz 600 Ft-ot.', '💰', 600, 0, 0, '[]', '[]', 1, 1, '#2e8b57', '#f2fff8'),
(2, 'chance', 'Bünti', 'Fizess 450 Ft-ot.', '💥', -450, 0, 0, '[]', '[]', 1, 1, '#9a3f54', '#fff0f3'),
(3, 'chance', 'Lépj előre', 'Lépj előre 2 mezőt.', '➡️', 0, 0, 2, '[]', '[]', 1, 1, '#5b52b4', '#f3efff'),
(4, 'chance', 'Lépj vissza', 'Lépj vissza 2 mezőt.', '↩️', 0, 0, -2, '[]', '[]', 1, 1, '#5b52b4', '#f3efff'),
(5, 'chance', 'Kimaradsz', '1 körből kimaradsz.', '😵', 0, 1, 0, '[]', '[]', 1, 1, '#9a3f54', '#fff0f3'),
(6, 'chance', 'Ajándék', 'Kapsz 1 random tárgyat.', '🎁', 0, 0, 0, '[]', '[1,2,3,4,5,6]', 1, 1, '#4762cc', '#eef2ff'),
(7, 'chance', 'Mini bolt', 'Válassz 1 tárgyat.', '🛒', 0, 0, 0, '[1,2,3,4,5,6]', '[]', 1, 1, '#8c6227', '#fff7e8'),
(8, 'chance', 'Nagy jutalom', 'Kapsz 1000 Ft-ot.', '🔥', 1000, 0, 0, '[]', '[]', 1, 1, '#2e8b57', '#f2fff8');

alter table public.game_config enable row level security;
alter table public.game_items enable row level security;
alter table public.game_tiles enable row level security;
alter table public.game_cards enable row level security;
alter table public.rooms enable row level security;
alter table public.room_players enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename='game_config' and policyname='p_game_config_all') then
    create policy p_game_config_all on public.game_config for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='game_items' and policyname='p_game_items_all') then
    create policy p_game_items_all on public.game_items for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='game_tiles' and policyname='p_game_tiles_all') then
    create policy p_game_tiles_all on public.game_tiles for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='game_cards' and policyname='p_game_cards_all') then
    create policy p_game_cards_all on public.game_cards for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='rooms' and policyname='p_rooms_all') then
    create policy p_rooms_all on public.rooms for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='room_players' and policyname='p_room_players_all') then
    create policy p_room_players_all on public.room_players for all using (true) with check (true);
  end if;
end $$;
